name: Latest Reddit RSS
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-reddit:
    name: Update this repo's README with latest rss from Reddit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "REDDIT"
          feed_list: "http://www.reddit.com/r/ErgoMechKeyboards/.rss"
          # https://www.reddit.com/r/ErgoMechKeyboards/.rss
